### ISSUE TITLE
Usage with other loop based library

### ISSUE THREAD

**Issue by mpkuse** [a-n-t-h-o-n-y/TermOx#40]
Hi,
I am considering CPPurses. I looked at the code samples and it looks pretty promising. Great Work!

In my workflow I use ros (Robot Operating System). ROS is an event loop based library. 
A sample loop looks something like
```
while( ros::ok() )
{
    rate.sleep(10)
    ros::spinOnce(); 
}
```

My question is:
Can CPPurses be used with ROS? If yes could you give me some pointers to get it running?

**Comment by a-n-t-h-o-n-y** [comment]
I'm a bit late here, but I'll still answer in case it helps anyone.

The `Event_loop` class can be used to create a separate thread from the main UI thread, an event loop object can be placed within some Widget type you create. The `void Event_loop::run_async(Fn loop_function)` function will launch a new thread and will repeatedly call the loop_function parameter with an `Event_queue&` parameter.

So in your example you could do something like this:

```cpp
struct My_widget : Widget {
    Event_loop loop_;
    My_widget() {
        loop_.run_async([this] (auto& queue) {
            if (!ros::ok())
                loop_.exit(1);
            rate.sleep(10);
            ros::spinOnce();
            queue.append(Paint_event{*this});
        });
    }
    auto paint_event(Painter& p) -> bool override {
        // use ROS data here in a thread safe way to update display.
        return Widget::paint_event(p);
    }
};
```

Every time the loop function returns, the event queue has a chance to process any events appended to it. In this case a `Paint_event` is appended, but in a more complex interaction, a `Custom_event` can be created, which can store a copy of the data from the event loop to be processed and displayed later, without any shared data threading issues.
