### ISSUE TITLE
[regression in 0.4] Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [a-n-t-h-o-n-y/TermOx#42]
cppurses-0.3 installed headers and the library, but termox-0.4 doesn't have the ```install``` target.

**Comment by a-n-t-h-o-n-y** [comment]
TermOx currently uses ncurses as a git submodule, and install of ncurses is tricky without hijacking the system default install, and cmake install commands are a bit of a mystery to me with something that isn't a cmake project(ncurses). I'll be attempting to replace ncurses very soon and hopefully that will enable the cmake file to have a simple enough install command again.

**Comment by yurivict** [comment]
```ncurses``` is available as a package on most systems.

**Comment by a-n-t-h-o-n-y** [comment]
I've had problems in the past with the various versions of `ncurses` that are installed across systems, keeping it as a submodule has fixed that, but its not quite 'right'. I'm working on a light weight alternative.

**Comment by a-n-t-h-o-n-y** [comment]
Latest `main` has install target now.
