### ISSUE TITLE
Please add a cmake variable for tests to build

### ISSUE THREAD

**Issue by yurivict** [a-n-t-h-o-n-y/TermOx#43]
Tests are only needed if the user wants to test. They are redundant in a package build.

Same for ```demos```.

**Comment by a-n-t-h-o-n-y** [comment]
The `main` branch currently only builds the library target on default builds; tests and demos have `EXCLUDE_FROM_ALL` set. The `termox-test` and `demos` targets are still generated, and those require the submodules to be initialized, but you need the submodules for the library to build.

I could add a cmake variable to not generate the test or demos targets, but I'm not seeing the target generation as an issue, unless I'm missing something?

**Comment by a-n-t-h-o-n-y** [comment]
I'll add the variables, I remember now you can't use submodules in package builds, and pulling in the extra dependency would be unnecessary.

**Comment by a-n-t-h-o-n-y** [comment]
This is added in the latest commit on `main`.

`TERMOX_BUILD_TESTS` and `TERMOX_BUILD_DEMOS` are now options that can be set at the command line to ON or OFF.

https://github.com/a-n-t-h-o-n-y/TermOx/commit/821cfdc55b4927a12587b6f659be10f9e917a58b
