### ISSUE TITLE
CMake Release Build Segmentation Fault

### ISSUE THREAD

**Issue by rgarber11** [a-n-t-h-o-n-y/TermOx#45]
Howdy!
I am very new to TermOx, so this may be an issue on my end, but my program runs into a Segmentation Fault when using Release settings on CMake. I am using GCC 10.2.

Here is a trace of the the threads:

![2021-04-19-053738_834x265_escrotum](https://user-images.githubusercontent.com/9834847/115215379-7109aa80-a0d1-11eb-8205-108d9b9d9082.png)

**Comment by rgarber11** [comment]
Update: I built with debugging info, so that what is happening is more clear. To clarify, this only happens with optimization.
![2021-04-19-055810_836x677_escrotum](https://user-images.githubusercontent.com/9834847/115218240-55ec6a00-a0d4-11eb-90bd-585d56014ac0.png)

**Comment by rgarber11** [comment]
Also note that I am using hideable.hpp in addition to termox.hpp

**Comment by rgarber11** [comment]
The Removal of Hideable fixes the issue.

**Comment by a-n-t-h-o-n-y** [comment]
Thanks for the info. The `develop` branch has replaced the code in the backtraces you provide, so the bug should be gone. This will be pushed to `main` soon.
