### ISSUE TITLE
Registering `SIGINT` internally in library

### ISSUE THREAD

**Issue by afshinpir** [a-n-t-h-o-n-y/TermOx#48]
Hi

I noticed that you can registered `SIGINT` internally in your library. It is somehow bad idea, because it conflict registering that signal in the code that uses your library. I suggest removing it from your library.

**Comment by a-n-t-h-o-n-y** [comment]
Thank you for catching this, I didn't know there could only be one handler. I've added a function to let you opt out of that behavior if you need it(`void Terminal::handle_sigint(bool)`).

The reason the library registers a function with the signal handler is to clean up the screen and leave it in a usable state, the screen will be left in a bad state after SIGINT if this is disabled.

https://github.com/a-n-t-h-o-n-y/TermOx/commit/469efa6f9d5584c663c1900535701e914ecdf7ea
