### ISSUE TITLE
How to show wide charaters

### ISSUE THREAD

**Issue by toge** [a-n-t-h-o-n-y/TermOx#49]
What a beautiful TUI library!
I just started using it. 

Is there any way to display the wide characters?
It doesn't seem to depend on ncurses anymore, do I still need to install ncursesw?

**Comment by a-n-t-h-o-n-y** [comment]
Hi,
This library uses `char32_t` to store each glyph displayed on the screen. I have noticed some issues on some terminals displaying emojis and other characters that do not physically fit within the mono-space cells that terminals have and being overwritten be neighboring cells.

You no longer need to install ncursesw, all dependencies are handled with git submodules.
